<?php
/** @var rex_addon $this */

use Cke5\Handler\Cke5DefaultDataService;
use Cke5\Handler\Cke5ExtensionHandler;
use Cke5\Utils\Cke5CssHandler;

include_once(__DIR__ . '/db.php');

// Setze den Standard-Lizenzschlüssel auf "GPL"
if ($this->getConfig('license_code') === null) {
    $this->setConfig('license_code', 'GPL');
}

$this->setConfig('restore_files', true);

try {
    Cke5DefaultDataService::importBundle($this->getPath('install/default_bundle.json'), ['demo_default', 'demo_light', 'demo_full_expert']);
    // copy custom data to assets folder
    if (!file_exists(rex_path::assets('addons/cke5_custom_data'))) {
        mkdir(rex_path::assets('addons/cke5_custom_data'));
    }
    if (!file_exists(rex_path::assets('addons/cke5_custom_data/custom-style.css'))) {
        rex_file::copy($this->getPath('custom_data/custom-styles.css'), rex_path::assets('addons/cke5_custom_data/custom-style.css'));
    }
    if (!file_exists(rex_path::assets('addons/cke5_custom_data/' . Cke5CssHandler::CSS_OUTPUT_FILE))) {
        rex_file::copy($this->getPath('custom_data/autogenerated-custom-styles.css'), rex_path::assets('addons/cke5_custom_data/' . Cke5CssHandler::CSS_OUTPUT_FILE));
    }
    // final create profiles
    Cke5ExtensionHandler::updateOrCreateProfiles();
} catch (rex_sql_exception $e) {
    rex_logger::logException($e);
    print rex_view::error($e->getMessage());
}
