package: cke5
version: '6.0.2'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/cke5/issues

page:
    title: 'translate:title'
    icon: cke5-icon-logo
    perm: admin
    subpages:
        main:
            title: 'translate:main'
            subpages:
                demo:
                    title: 'translate:demo'
                preview:
                    title: 'translate:preview'
        profiles:
            title: 'translate:profiles'
            subpages:
                overview:
                    title: 'translate:profiles'
                export:
                    title: 'translate:profiles_export'
                import:
                    title: 'translate:profiles_import'
        help:
             title: 'translate:help'
             subPath: README.md
        licenses:
             title: 'translate:licenses'
             subPath: LICENSE.md     
requires:
    redaxo: '^5.12'
    php:
        version: '>=7.2, <9'
conflicts:
    packages:
        mblock: '<3.4.0'
        mform: '<6.1.0'
