package: cke5
version: '5.0.0-dev'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/cke5/issues

page:
    title: 'translate:title'
    icon: cke5-icon-logo
    perm: admin
    subpages:
        main:
            title: 'translate:main'
            subpages:
                demo:
                    title: 'translate:demo'
                preview:
                    title: 'translate:preview'
        profiles:
            title: 'translate:profiles'
        help:
             { title: 'translate:help', subPath: README.md }

requires:
    redaxo: '^5.7'
    php:
        version: '>=7.1, <9'
