<?php
/** @var rex_addon $this */

use Cke5\Handler\Cke5DefaultDataService;
use Cke5\Handler\Cke5ExtensionHandler;

include_once (__DIR__ . '/db.php');

// Setze den Standard-Lizenzschlüssel auf "GPL", falls er noch nicht existiert
if ($this->getConfig('license_code') === null || $this->getConfig('license_code') === '') {
    $this->setConfig('license_code', 'GPL');
}

$this->setConfig('restore_files', true);

try {
    Cke5DefaultDataService::importBundle($this->getPath('install/default_bundle.json'), ['demo_default', 'demo_light', 'demo_full_expert']);

    if (!file_exists(rex_path::assets('addons/cke5_custom_data'))) {
        mkdir(rex_path::assets('addons/cke5_custom_data'));
    }

    if (!file_exists(rex_path::assets('addons/cke5_custom_data/custom-style.css'))) {
        rex_file::copy($this->getPath('custom_data/custom-styles.css'), rex_path::assets('addons/cke5_custom_data/custom-style.css'));
    }

    if (!file_exists(rex_path::assets('addons/cke5_custom_data/autogenerated-custom-styles.css'))) {
        rex_file::copy($this->getPath('custom_data/autogenerated-custom-styles.css'), rex_path::assets('addons/cke5_custom_data/autogenerated-custom-style.css'));
    }

    try {
        rex_sql::factory()->setQuery('DROP TABLE IF EXISTS ' . rex::getTablePrefix() . 'cke5_mblock_demo');
    } catch (rex_sql_exception $e) {
        rex_logger::logException($e);
    }
} catch (rex_functional_exception $e) {
    rex_logger::logException($e);
}

Cke5ExtensionHandler::updateOrCreateProfiles();

$addon = rex_addon::get('cke5');
$addon->setConfig('updated', true);
