<?php
/** @var rex_addon $this */

use Cke5\Handler\Cke5DefaultDataService;
use Cke5\Handler\Cke5ExtensionHandler;

include_once (__DIR__ . '/db.php');

// Setze den Standard-Lizenzschlüssel auf "GPL", falls er noch nicht existiert
if ($this->getConfig('license_code') === null || $this->getConfig('license_code') === '') {
    $this->setConfig('license_code', 'GPL');
}

$this->setConfig('restore_files', true);

try {
    Cke5DefaultDataService::importBundle($this->getPath('install/default_bundle.json'), ['demo_default', 'demo_light', 'demo_full_expert']);

    if ($this->getConfig('image_resize_handles_restored') !== true) {
        rex_sql::factory()->setQuery(
            'UPDATE ' . rex::getTable('cke5_profiles') . ' SET image_resize_handles = :image_resize_handles WHERE image_resize_handles IS NULL OR image_resize_handles = :empty_value',
            [
                'image_resize_handles' => '|default_resize_handles|',
                'empty_value' => '',
            ]
        );
        $this->setConfig('image_resize_handles_restored', true);
    }

    if (!file_exists(rex_path::assets('addons/cke5_custom_data'))) {
        mkdir(rex_path::assets('addons/cke5_custom_data'));
    }

    if (!file_exists(rex_path::assets('addons/cke5_custom_data/custom-style.css'))) {
        rex_file::copy($this->getPath('custom_data/custom-styles.css'), rex_path::assets('addons/cke5_custom_data/custom-style.css'));
    }

    if (!file_exists(rex_path::assets('addons/cke5_custom_data/autogenerated-custom-style.css'))) {
        rex_file::copy($this->getPath('custom_data/autogenerated-custom-styles.css'), rex_path::assets('addons/cke5_custom_data/autogenerated-custom-style.css'));
    }

    try {
        rex_sql::factory()->setQuery('DROP TABLE IF EXISTS ' . rex::getTablePrefix() . 'cke5_mblock_demo');

        // Legacy-Tabellen aus älteren Versionen aufräumen
        if (rex_sql_table::get(rex::getTable('cke5_templates'))->exists()) {
            rex_sql::factory()->setQuery('DROP TABLE IF EXISTS ' . rex::getTablePrefix() . 'cke5_templates');
        }
        if (rex_sql_table::get(rex::getTable('cke5_template_groups'))->exists()) {
            rex_sql::factory()->setQuery('DROP TABLE IF EXISTS ' . rex::getTablePrefix() . 'cke5_template_groups');
        }
    } catch (rex_sql_exception $e) {
        rex_logger::logException($e);
    }
} catch (rex_functional_exception $e) {
    rex_logger::logException($e);
}

Cke5ExtensionHandler::updateOrCreateProfiles();

$addon = rex_addon::get('cke5');
$addon->setConfig('updated', true);
